# Generated by Django 4.0 on 2023-03-27 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('create_deta', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='drone_booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.CharField(max_length=255)),
                ('drone_shot_id', models.CharField(max_length=255)),
                ('booking_date', models.DateTimeField()),
                ('create_deta', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone_booking.customers')),
            ],
        ),
    ]
