# Generated by Django 4.0 on 2023-03-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_booking', '0002_alter_customers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone_booking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
